/// <reference types="@cloudflare/vitest-pool-workers/types" />

// The test env (`import { env } from "cloudflare:test"`) provides the same
// bindings as the worker. `Cloudflare.Env` is generated by `wrangler types`.
declare module "cloudflare:test" {
  interface ProvidedEnv extends Cloudflare.Env {}
}
